version: "3.9"
services:
  
   discovery-service:
     image: discovery-service
     ports:
       - 8761:8761
     volumes:
       - ./log:/var/log

   api-gateway:
     image: api-gateway
     environment:
       - SPRING_PROFILES_ACTIVE=default,eureka
       - EUREKA_HOST=discovery-service
       - EUREKA_PORT=8761
       # OpenTelemetry
       - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
       - OTEL_TRACES_EXPORTER=otlp
       - OTEL_METRICS_EXPORTER=none
       - OTEL_LOGS_EXPORTER=none
       - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
       - OTEL_SERVICE_NAME=api-gateway
     ports:
       - 8765:8765
     volumes:
       - ./log:/var/log
     depends_on:
      - discovery-service
      - otel-collector

   service-a:
     image: kambei/service-a:1.0.0-SNAPSHOT
     volumes:
       - ./log:/var/log
     user: root
     depends_on:
       - discovery-service
       - otel-collector

   service-b:
     image: kambei/service-b:1.0.0-SNAPSHOT
     volumes:
       - ./log:/var/log
     user: root
     depends_on:
       - discovery-service
       - otel-collector

   ##--------------------------MONITORING-------------------------------------------##
   prometheus-rsocket-proxy:
     image: micrometermetrics/prometheus-rsocket-proxy
     container_name: prometheus-rsocket-proxy
     expose:
       - '9096'
       - '7001'
       - '8086'
     # ports:
     #   - '9096:9096'
     #   - '7001:7001'
     #   - '8086:8086'
     environment:
       - server.port=9096
       - micrometer.prometheus-proxy.websocket-port=8086
       - micrometer.prometheus-proxy.tcp-port=7001

   prometheus:
     image: prom/prometheus
     ports:
        - ${PROMETHEUS_EXTERNAL_PORT:-19090}:9090
     volumes:
       - ./tracing/prometheus/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml:cached
     depends_on:
       - prometheus-rsocket-proxy

   promtail:
     image: grafana/promtail
     volumes:
       - ${LOG_MOUNT_PATH:-./log}:/var/log
       - ./tracing/promtail/:/mnt/config
     command: -config.file=/mnt/config/promtail-config.yaml

   loki:
     image: grafana/loki
     command: -config.file=/etc/loki/local-config.yaml
     volumes:
       - ./tracing/loki:/etc/loki:cached
     depends_on:
       - promtail

   otel-collector:
     image: otel/opentelemetry-collector
     command: [ "--config=/etc/otel-collector-config.yaml" ]
     volumes:
       - ./tracing/otel/otel-config.yml:/etc/otel-collector-config.yaml
     ports:
       - "1888:1888"   # pprof extension
       - "13133:13133" # health_check extension
       - "4317:4317"        # OTLP gRPC receiver
       - "55679:55679" # zpages extension
     depends_on:
       - tempo

   tempo:
     image: grafana/tempo
     command: [ "-config.file=/etc/tempo.yaml" ]
     volumes:
       - ./tracing/tempo/tempo-local.yaml:/etc/tempo.yaml:cached
       # - ./tempo-data/:/tmp/tempo
     ports:
       - "14268"      # jaeger ingest, Jaeger - Thrift HTTP
       - "14250"      # Jaeger - GRPC
       - "55680"      # OpenTelemetry
       - "3200"       # tempo
       - "6831/udp"   # Jaeger - Thrift Compact
       - "6832/udp"   # Jaeger - Thrift Binary

   grafana:
     image: grafana/grafana
     volumes:
       - ./tracing/grafana/datasource-config/:/etc/grafana/provisioning/datasources:cached
       - ./tracing/grafana/dashboards-config/:/etc/grafana/provisioning/dashboards:cached
     ports:
       - ${GRAFANA_EXTERNAL_PORT:-13000}:3000
     # environment:
     #   - GF_AUTH_ANONYMOUS_ENABLED=true
     #   - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     #   - GF_AUTH_DISABLE_LOGIN_FORM=true
     depends_on:
       - prometheus
       - loki
       - tempo

