server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
    register-with-eureka: false
    fetch-registry: false

# ACTUATORS
management.endpoints.jmx.exposure.exclude:
management.endpoints.jmx.exposure.include: info,health,env,loggers,metrics,prometheus
management.endpoints.web.exposure.exclude:
management.endpoints.web.exposure.include: info,health,env,loggers,metrics,prometheus
management.endpoint.info.enabled: true
management.endpoint.loggers.enabled: true

# Logging
logging.file.name: /var/log/${spring.application.name}.log
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 1
      clean-history-on-start: true

# METRICS
management:
  metrics:
    tags:
      application: discovery-service
management.metrics.export.prometheus.enabled: true
management.metrics.export.prometheus.rsocket:
  host: prometheus-rsocket-proxy #required
  port: 7001
  max-retries: 10000 # default is Long.MAX_VALUE
  first-backoff: 10s
  max-backoff: 10m
